import { useCallback, useMemo, useState, type DragEvent, type ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import {
  FileUp,
  FolderOpen,
  MapPin,
  Upload,
  X,
} from "lucide-react";
import type { TFunction } from "i18next";

import { AgentAvatar } from "@/components/agents/agent-avatar";
import { DogAvatar } from "@/components/dogs/dog-avatar";
import { StatusBadge } from "@/components/enterprise/status-badge";
import { cn } from "@/lib/utils";
import {
  caseSpecialtyBadgeTone,
  caseSpecialtyLabel,
} from "@/lib/operational-cases";
import type { OperationalCaseSpecialty } from "@/lib/operational-case-form";

export function DialogSectionCard({
  title,
  icon: Icon,
  children,
  className,
}: {
  title: string;
  icon: LucideIcon;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section
      className={cn(
        "rounded-2xl border border-border/60 bg-card p-5 shadow-soft transition-shadow duration-200 hover:shadow-card",
        className,
      )}
    >
      <header className="mb-4 flex items-center gap-2.5 border-b border-border/40 pb-3">
        <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-primary/10 text-primary">
          <Icon className="h-4 w-4" strokeWidth={2.25} />
        </span>
        <h3 className="text-sm font-semibold tracking-tight text-foreground">{title}</h3>
      </header>
      {children}
    </section>
  );
}

export function IconFormField({
  label,
  icon: Icon,
  error,
  children,
  className,
}: {
  label: string;
  icon: LucideIcon;
  error?: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <div className={cn("grid gap-2", className)}>
      <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        <Icon className="h-3.5 w-3.5 shrink-0 text-primary/80" strokeWidth={2.25} />
        {label}
      </label>
      <div className="[&_input]:rounded-xl [&_input]:transition-all [&_input]:duration-200 [&_input]:focus-visible:ring-2 [&_input]:focus-visible:ring-primary/25 [&_button[role=combobox]]:rounded-xl [&_button[role=combobox]]:transition-all [&_button[role=combobox]]:duration-200 [&_button[role=combobox]]:focus-visible:ring-2 [&_button[role=combobox]]:focus-visible:ring-primary/25 [&_textarea]:rounded-xl [&_textarea]:transition-all [&_textarea]:duration-200 [&_textarea]:focus-visible:ring-2 [&_textarea]:focus-visible:ring-primary/25">
        {children}
      </div>
      {error ? <p className="text-xs font-medium text-destructive">{error}</p> : null}
    </div>
  );
}

export function CaseDialogHeader({
  title,
  subtitle,
  caseNumber,
  caseNumberLoading,
  caseNumberLabel,
  autoGeneratedLabel,
}: {
  title: string;
  subtitle: string;
  caseNumber: string;
  caseNumberLoading?: boolean;
  caseNumberLabel: string;
  autoGeneratedLabel?: string;
}) {
  return (
    <header className="flex shrink-0 flex-col gap-4 border-b border-border/50 bg-gradient-to-r from-muted/30 via-card to-card px-6 py-5 sm:flex-row sm:items-start sm:justify-between">
      <div className="min-w-0 space-y-1">
        <div className="flex items-center gap-2.5">
          <span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10 text-primary shadow-soft">
            <FolderOpen className="h-5 w-5" strokeWidth={2.25} />
          </span>
          <div>
            <h2 className="text-lg font-semibold tracking-tight text-foreground">{title}</h2>
            <p className="text-sm text-muted-foreground">{subtitle}</p>
          </div>
        </div>
      </div>
      <div className="shrink-0 rounded-2xl border border-primary/20 bg-primary/5 px-4 py-3 shadow-soft">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-primary/80">{caseNumberLabel}</p>
        <p className="mt-0.5 font-mono text-base font-bold tabular-nums text-primary">
          {caseNumberLoading ? "…" : caseNumber || "—"}
        </p>
        {autoGeneratedLabel ? (
          <p className="mt-1 text-[10px] font-medium text-muted-foreground">{autoGeneratedLabel}</p>
        ) : null}
      </div>
    </header>
  );
}

export function CaseDialogSidebar({
  todayLabel,
  agent,
  dogName,
  dogPhotoUrl,
  dogSpecialty,
  checkpointName,
  specialty,
  caseNumber,
  caseNumberLoading,
  t,
}: {
  todayLabel: string;
  agent?: {
    first_name: string;
    last_name: string;
    professional_number: string;
    photo_url?: string | null;
  } | null;
  dogName?: string;
  dogPhotoUrl?: string | null;
  dogSpecialty?: "narcotics" | "explosives" | "currency" | null;
  checkpointName?: string;
  specialty: OperationalCaseSpecialty;
  caseNumber: string;
  caseNumberLoading?: boolean;
  t: TFunction;
}) {
  return (
    <aside className="hidden w-[280px] shrink-0 flex-col border-l border-border/50 bg-muted/20 lg:flex">
      <div className="space-y-5 p-5">
        <div className="rounded-2xl border border-border/50 bg-card p-4 shadow-soft">
          <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            {t("operationalCases.dialog.sidebar.today")}
          </p>
          <p className="mt-1 text-sm font-semibold tabular-nums">{todayLabel}</p>
        </div>

        <div className="rounded-2xl border border-border/50 bg-card p-4 shadow-soft">
          <p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            {t("operationalCases.field.agent")}
          </p>
          {agent ? (
            <div className="flex items-center gap-3">
              <AgentAvatar
                firstName={agent.first_name}
                lastName={agent.last_name}
                photoUrl={agent.photo_url}
                className="h-12 w-12"
              />
              <div className="min-w-0">
                <p className="truncate text-sm font-semibold">
                  {agent.first_name} {agent.last_name}
                </p>
                <p className="truncate font-mono text-[10px] text-muted-foreground">{agent.professional_number}</p>
              </div>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">{t("common.none")}</p>
          )}
        </div>

        <div className="rounded-2xl border border-border/50 bg-card p-4 shadow-soft">
          <p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            {t("operationalCases.field.dog")}
          </p>
          {dogName ? (
            <div className="flex items-center gap-3">
              <DogAvatar name={dogName} photoUrl={dogPhotoUrl} specialty={dogSpecialty} className="h-11 w-11" />
              <p className="truncate text-sm font-semibold">{dogName}</p>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">{t("common.none")}</p>
          )}
        </div>

        <div className="space-y-2">
          {checkpointName ? (
            <StatusBadge tone="neutral" className="w-full justify-center gap-1.5 px-3 py-1.5 text-xs">
              <MapPin className="h-3.5 w-3.5" />
              {checkpointName}
            </StatusBadge>
          ) : null}
          <StatusBadge tone={caseSpecialtyBadgeTone(specialty)} className="w-full justify-center px-3 py-1.5 text-xs">
            {caseSpecialtyLabel(specialty, t)}
          </StatusBadge>
        </div>

        <div className="rounded-2xl border border-primary/20 bg-primary/5 p-4">
          <p className="text-[10px] font-semibold uppercase tracking-wider text-primary/80">
            {t("operationalCases.field.caseNumber")}
          </p>
          <p className="mt-1 font-mono text-sm font-bold text-primary">
            {caseNumberLoading ? "…" : caseNumber || "—"}
          </p>
        </div>
      </div>
    </aside>
  );
}

export function CaseDialogFooter({
  onCancel,
  onSubmit,
  submitLabel,
  cancelLabel,
  isPending,
}: {
  onCancel: () => void;
  onSubmit: () => void;
  submitLabel: string;
  cancelLabel: string;
  isPending?: boolean;
}) {
  return (
    <footer className="flex shrink-0 items-center justify-between gap-3 border-t border-border/50 bg-card/95 px-6 py-4 backdrop-blur-sm">
      <button
        type="button"
        onClick={onCancel}
        className="rounded-xl px-4 py-2.5 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
      >
        {cancelLabel}
      </button>
      <button
        type="button"
        onClick={onSubmit}
        disabled={isPending}
        className="inline-flex min-w-[160px] items-center justify-center rounded-xl bg-primary px-6 py-2.5 text-sm font-semibold text-primary-foreground shadow-soft transition-all duration-200 hover:bg-primary/90 hover:shadow-card disabled:opacity-60"
      >
        {isPending ? "…" : submitLabel}
      </button>
    </footer>
  );
}

type AttachmentDropzoneProps = {
  files: File[];
  onFilesChange: (files: File[]) => void;
  label: string;
  hint: string;
  pendingLabel: (count: number) => string;
};

export function AttachmentDropzone({ files, onFilesChange, label, hint, pendingLabel }: AttachmentDropzoneProps) {
  const [dragging, setDragging] = useState(false);

  const previews = useMemo(
    () =>
      files.map((file) => ({
        file,
        url: file.type.startsWith("image/") ? URL.createObjectURL(file) : null,
      })),
    [files],
  );

  const addFiles = useCallback(
    (incoming: FileList | File[]) => {
      const list = Array.from(incoming);
      if (list.length === 0) return;
      onFilesChange([...files, ...list]);
    },
    [files, onFilesChange],
  );

  const onDrop = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setDragging(false);
    addFiles(event.dataTransfer.files);
  };

  const removeFile = (index: number) => {
    onFilesChange(files.filter((_, i) => i !== index));
  };

  return (
    <div className="grid gap-3">
      <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        <FileUp className="h-3.5 w-3.5 text-primary/80" />
        {label}
      </label>
      <div
        onDragOver={(e) => {
          e.preventDefault();
          setDragging(true);
        }}
        onDragLeave={() => setDragging(false)}
        onDrop={onDrop}
        className={cn(
          "relative flex min-h-[140px] cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed px-4 py-8 text-center transition-all duration-200",
          dragging
            ? "border-primary bg-primary/5 shadow-inner"
            : "border-border/70 bg-muted/20 hover:border-primary/40 hover:bg-primary/[0.03]",
        )}
      >
        <input
          type="file"
          multiple
          className="absolute inset-0 cursor-pointer opacity-0"
          onChange={(e) => {
            addFiles(e.target.files ?? []);
            e.target.value = "";
          }}
        />
        <span className="mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
          <Upload className="h-5 w-5" />
        </span>
        <p className="text-sm font-medium text-foreground">{hint}</p>
        {files.length > 0 ? (
          <p className="mt-1 text-xs text-muted-foreground">{pendingLabel(files.length)}</p>
        ) : null}
      </div>

      {previews.length > 0 ? (
        <ul className="grid grid-cols-2 gap-3 sm:grid-cols-3">
          {previews.map(({ file, url }, index) => (
            <li
              key={`${file.name}-${index}`}
              className="group relative overflow-hidden rounded-xl border border-border/60 bg-card shadow-soft"
            >
              {url ? (
                <img src={url} alt={file.name} className="aspect-video w-full object-cover" />
              ) : (
                <div className="flex aspect-video items-center justify-center bg-muted/40 p-3">
                  <FileUp className="h-8 w-8 text-muted-foreground/50" />
                </div>
              )}
              <div className="truncate px-2 py-1.5 text-[10px] font-medium text-muted-foreground">{file.name}</div>
              <button
                type="button"
                onClick={() => removeFile(index)}
                className="absolute right-1.5 top-1.5 flex h-6 w-6 items-center justify-center rounded-full bg-background/90 text-muted-foreground opacity-0 shadow-sm transition-opacity group-hover:opacity-100 hover:text-destructive"
                aria-label="Remove"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}

export function ReadFieldCard({
  icon: Icon,
  label,
  value,
}: {
  icon: LucideIcon;
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-xl border border-border/50 bg-muted/20 p-3 transition-colors hover:bg-muted/30">
      <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
        <Icon className="h-3.5 w-3.5 text-primary/70" />
        {label}
      </div>
      <p className="mt-1.5 text-sm font-medium leading-snug">{value}</p>
    </div>
  );
}
