/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSectionsRouteImport } from './routes/_authenticated/sections'
import { Route as AuthenticatedReportsMessagesRouteImport } from './routes/_authenticated/reports-messages'
import { Route as AuthenticatedOperationalCasesRouteImport } from './routes/_authenticated/operational-cases'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExclusionsRouteImport } from './routes/_authenticated/exclusions'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDogsRouteImport } from './routes/_authenticated/dogs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyPlanningRouteImport } from './routes/_authenticated/daily-planning'
import { Route as AuthenticatedCheckpointsRouteImport } from './routes/_authenticated/checkpoints'
import { Route as AuthenticatedReportsMessagesIndexRouteImport } from './routes/_authenticated/reports-messages.index'
import { Route as AuthenticatedReportsMessagesVeterinaryRouteImport } from './routes/_authenticated/reports-messages.veterinary'
import { Route as AuthenticatedReportsMessagesTemplatesRouteImport } from './routes/_authenticated/reports-messages.templates'
import { Route as AuthenticatedReportsMessagesSecretaryRouteImport } from './routes/_authenticated/reports-messages.secretary'
import { Route as AuthenticatedReportsMessagesEquipmentChiefRouteImport } from './routes/_authenticated/reports-messages.equipment-chief'
import { Route as AuthenticatedReportsMessagesAssistantRouteImport } from './routes/_authenticated/reports-messages.assistant'
import { Route as AuthenticatedDogsIdRouteImport } from './routes/_authenticated/dogs.$id'
import { Route as AuthenticatedReportsMessagesTemplatesIndexRouteImport } from './routes/_authenticated/reports-messages.templates.index'
import { Route as AuthenticatedReportsMessagesTemplatesTemplateIdRouteImport } from './routes/_authenticated/reports-messages.templates.$templateId'
import { Route as AuthenticatedReportsMessagesRoleCategoryDocumentIdRouteImport } from './routes/_authenticated/reports-messages.$roleCategory.$documentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSectionsRoute = AuthenticatedSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsMessagesRoute =
  AuthenticatedReportsMessagesRouteImport.update({
    id: '/reports-messages',
    path: '/reports-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationalCasesRoute =
  AuthenticatedOperationalCasesRouteImport.update({
    id: '/operational-cases',
    path: '/operational-cases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExclusionsRoute = AuthenticatedExclusionsRouteImport.update({
  id: '/exclusions',
  path: '/exclusions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDogsRoute = AuthenticatedDogsRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyPlanningRoute =
  AuthenticatedDailyPlanningRouteImport.update({
    id: '/daily-planning',
    path: '/daily-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckpointsRoute =
  AuthenticatedCheckpointsRouteImport.update({
    id: '/checkpoints',
    path: '/checkpoints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMessagesIndexRoute =
  AuthenticatedReportsMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)
const AuthenticatedReportsMessagesVeterinaryRoute =
  AuthenticatedReportsMessagesVeterinaryRouteImport.update({
    id: '/veterinary',
    path: '/veterinary',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)
const AuthenticatedReportsMessagesTemplatesRoute =
  AuthenticatedReportsMessagesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)
const AuthenticatedReportsMessagesSecretaryRoute =
  AuthenticatedReportsMessagesSecretaryRouteImport.update({
    id: '/secretary',
    path: '/secretary',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)
const AuthenticatedReportsMessagesEquipmentChiefRoute =
  AuthenticatedReportsMessagesEquipmentChiefRouteImport.update({
    id: '/equipment-chief',
    path: '/equipment-chief',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)
const AuthenticatedReportsMessagesAssistantRoute =
  AuthenticatedReportsMessagesAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)
const AuthenticatedDogsIdRoute = AuthenticatedDogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDogsRoute,
} as any)
const AuthenticatedReportsMessagesTemplatesIndexRoute =
  AuthenticatedReportsMessagesTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsMessagesTemplatesRoute,
  } as any)
const AuthenticatedReportsMessagesTemplatesTemplateIdRoute =
  AuthenticatedReportsMessagesTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AuthenticatedReportsMessagesTemplatesRoute,
  } as any)
const AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute =
  AuthenticatedReportsMessagesRoleCategoryDocumentIdRouteImport.update({
    id: '/$roleCategory/$documentId',
    path: '/$roleCategory/$documentId',
    getParentRoute: () => AuthenticatedReportsMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/daily-planning': typeof AuthenticatedDailyPlanningRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dogs': typeof AuthenticatedDogsRouteWithChildren
  '/employees': typeof AuthenticatedEmployeesRoute
  '/exclusions': typeof AuthenticatedExclusionsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/operational-cases': typeof AuthenticatedOperationalCasesRoute
  '/reports-messages': typeof AuthenticatedReportsMessagesRouteWithChildren
  '/sections': typeof AuthenticatedSectionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/dogs/$id': typeof AuthenticatedDogsIdRoute
  '/reports-messages/assistant': typeof AuthenticatedReportsMessagesAssistantRoute
  '/reports-messages/equipment-chief': typeof AuthenticatedReportsMessagesEquipmentChiefRoute
  '/reports-messages/secretary': typeof AuthenticatedReportsMessagesSecretaryRoute
  '/reports-messages/templates': typeof AuthenticatedReportsMessagesTemplatesRouteWithChildren
  '/reports-messages/veterinary': typeof AuthenticatedReportsMessagesVeterinaryRoute
  '/reports-messages/': typeof AuthenticatedReportsMessagesIndexRoute
  '/reports-messages/$roleCategory/$documentId': typeof AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute
  '/reports-messages/templates/$templateId': typeof AuthenticatedReportsMessagesTemplatesTemplateIdRoute
  '/reports-messages/templates/': typeof AuthenticatedReportsMessagesTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/daily-planning': typeof AuthenticatedDailyPlanningRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dogs': typeof AuthenticatedDogsRouteWithChildren
  '/employees': typeof AuthenticatedEmployeesRoute
  '/exclusions': typeof AuthenticatedExclusionsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/operational-cases': typeof AuthenticatedOperationalCasesRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/dogs/$id': typeof AuthenticatedDogsIdRoute
  '/reports-messages/assistant': typeof AuthenticatedReportsMessagesAssistantRoute
  '/reports-messages/equipment-chief': typeof AuthenticatedReportsMessagesEquipmentChiefRoute
  '/reports-messages/secretary': typeof AuthenticatedReportsMessagesSecretaryRoute
  '/reports-messages/veterinary': typeof AuthenticatedReportsMessagesVeterinaryRoute
  '/reports-messages': typeof AuthenticatedReportsMessagesIndexRoute
  '/reports-messages/$roleCategory/$documentId': typeof AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute
  '/reports-messages/templates/$templateId': typeof AuthenticatedReportsMessagesTemplatesTemplateIdRoute
  '/reports-messages/templates': typeof AuthenticatedReportsMessagesTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/_authenticated/daily-planning': typeof AuthenticatedDailyPlanningRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dogs': typeof AuthenticatedDogsRouteWithChildren
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/exclusions': typeof AuthenticatedExclusionsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/operational-cases': typeof AuthenticatedOperationalCasesRoute
  '/_authenticated/reports-messages': typeof AuthenticatedReportsMessagesRouteWithChildren
  '/_authenticated/sections': typeof AuthenticatedSectionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/dogs/$id': typeof AuthenticatedDogsIdRoute
  '/_authenticated/reports-messages/assistant': typeof AuthenticatedReportsMessagesAssistantRoute
  '/_authenticated/reports-messages/equipment-chief': typeof AuthenticatedReportsMessagesEquipmentChiefRoute
  '/_authenticated/reports-messages/secretary': typeof AuthenticatedReportsMessagesSecretaryRoute
  '/_authenticated/reports-messages/templates': typeof AuthenticatedReportsMessagesTemplatesRouteWithChildren
  '/_authenticated/reports-messages/veterinary': typeof AuthenticatedReportsMessagesVeterinaryRoute
  '/_authenticated/reports-messages/': typeof AuthenticatedReportsMessagesIndexRoute
  '/_authenticated/reports-messages/$roleCategory/$documentId': typeof AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute
  '/_authenticated/reports-messages/templates/$templateId': typeof AuthenticatedReportsMessagesTemplatesTemplateIdRoute
  '/_authenticated/reports-messages/templates/': typeof AuthenticatedReportsMessagesTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkpoints'
    | '/daily-planning'
    | '/dashboard'
    | '/dogs'
    | '/employees'
    | '/exclusions'
    | '/history'
    | '/operational-cases'
    | '/reports-messages'
    | '/sections'
    | '/settings'
    | '/statistics'
    | '/dogs/$id'
    | '/reports-messages/assistant'
    | '/reports-messages/equipment-chief'
    | '/reports-messages/secretary'
    | '/reports-messages/templates'
    | '/reports-messages/veterinary'
    | '/reports-messages/'
    | '/reports-messages/$roleCategory/$documentId'
    | '/reports-messages/templates/$templateId'
    | '/reports-messages/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkpoints'
    | '/daily-planning'
    | '/dashboard'
    | '/dogs'
    | '/employees'
    | '/exclusions'
    | '/history'
    | '/operational-cases'
    | '/sections'
    | '/settings'
    | '/statistics'
    | '/dogs/$id'
    | '/reports-messages/assistant'
    | '/reports-messages/equipment-chief'
    | '/reports-messages/secretary'
    | '/reports-messages/veterinary'
    | '/reports-messages'
    | '/reports-messages/$roleCategory/$documentId'
    | '/reports-messages/templates/$templateId'
    | '/reports-messages/templates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/checkpoints'
    | '/_authenticated/daily-planning'
    | '/_authenticated/dashboard'
    | '/_authenticated/dogs'
    | '/_authenticated/employees'
    | '/_authenticated/exclusions'
    | '/_authenticated/history'
    | '/_authenticated/operational-cases'
    | '/_authenticated/reports-messages'
    | '/_authenticated/sections'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/dogs/$id'
    | '/_authenticated/reports-messages/assistant'
    | '/_authenticated/reports-messages/equipment-chief'
    | '/_authenticated/reports-messages/secretary'
    | '/_authenticated/reports-messages/templates'
    | '/_authenticated/reports-messages/veterinary'
    | '/_authenticated/reports-messages/'
    | '/_authenticated/reports-messages/$roleCategory/$documentId'
    | '/_authenticated/reports-messages/templates/$templateId'
    | '/_authenticated/reports-messages/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sections': {
      id: '/_authenticated/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AuthenticatedSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports-messages': {
      id: '/_authenticated/reports-messages'
      path: '/reports-messages'
      fullPath: '/reports-messages'
      preLoaderRoute: typeof AuthenticatedReportsMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operational-cases': {
      id: '/_authenticated/operational-cases'
      path: '/operational-cases'
      fullPath: '/operational-cases'
      preLoaderRoute: typeof AuthenticatedOperationalCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exclusions': {
      id: '/_authenticated/exclusions'
      path: '/exclusions'
      fullPath: '/exclusions'
      preLoaderRoute: typeof AuthenticatedExclusionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dogs': {
      id: '/_authenticated/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof AuthenticatedDogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-planning': {
      id: '/_authenticated/daily-planning'
      path: '/daily-planning'
      fullPath: '/daily-planning'
      preLoaderRoute: typeof AuthenticatedDailyPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkpoints': {
      id: '/_authenticated/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof AuthenticatedCheckpointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports-messages/': {
      id: '/_authenticated/reports-messages/'
      path: '/'
      fullPath: '/reports-messages/'
      preLoaderRoute: typeof AuthenticatedReportsMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
    '/_authenticated/reports-messages/veterinary': {
      id: '/_authenticated/reports-messages/veterinary'
      path: '/veterinary'
      fullPath: '/reports-messages/veterinary'
      preLoaderRoute: typeof AuthenticatedReportsMessagesVeterinaryRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
    '/_authenticated/reports-messages/templates': {
      id: '/_authenticated/reports-messages/templates'
      path: '/templates'
      fullPath: '/reports-messages/templates'
      preLoaderRoute: typeof AuthenticatedReportsMessagesTemplatesRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
    '/_authenticated/reports-messages/secretary': {
      id: '/_authenticated/reports-messages/secretary'
      path: '/secretary'
      fullPath: '/reports-messages/secretary'
      preLoaderRoute: typeof AuthenticatedReportsMessagesSecretaryRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
    '/_authenticated/reports-messages/equipment-chief': {
      id: '/_authenticated/reports-messages/equipment-chief'
      path: '/equipment-chief'
      fullPath: '/reports-messages/equipment-chief'
      preLoaderRoute: typeof AuthenticatedReportsMessagesEquipmentChiefRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
    '/_authenticated/reports-messages/assistant': {
      id: '/_authenticated/reports-messages/assistant'
      path: '/assistant'
      fullPath: '/reports-messages/assistant'
      preLoaderRoute: typeof AuthenticatedReportsMessagesAssistantRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
    '/_authenticated/dogs/$id': {
      id: '/_authenticated/dogs/$id'
      path: '/$id'
      fullPath: '/dogs/$id'
      preLoaderRoute: typeof AuthenticatedDogsIdRouteImport
      parentRoute: typeof AuthenticatedDogsRoute
    }
    '/_authenticated/reports-messages/templates/': {
      id: '/_authenticated/reports-messages/templates/'
      path: '/'
      fullPath: '/reports-messages/templates/'
      preLoaderRoute: typeof AuthenticatedReportsMessagesTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesTemplatesRoute
    }
    '/_authenticated/reports-messages/templates/$templateId': {
      id: '/_authenticated/reports-messages/templates/$templateId'
      path: '/$templateId'
      fullPath: '/reports-messages/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedReportsMessagesTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesTemplatesRoute
    }
    '/_authenticated/reports-messages/$roleCategory/$documentId': {
      id: '/_authenticated/reports-messages/$roleCategory/$documentId'
      path: '/$roleCategory/$documentId'
      fullPath: '/reports-messages/$roleCategory/$documentId'
      preLoaderRoute: typeof AuthenticatedReportsMessagesRoleCategoryDocumentIdRouteImport
      parentRoute: typeof AuthenticatedReportsMessagesRoute
    }
  }
}

interface AuthenticatedDogsRouteChildren {
  AuthenticatedDogsIdRoute: typeof AuthenticatedDogsIdRoute
}

const AuthenticatedDogsRouteChildren: AuthenticatedDogsRouteChildren = {
  AuthenticatedDogsIdRoute: AuthenticatedDogsIdRoute,
}

const AuthenticatedDogsRouteWithChildren =
  AuthenticatedDogsRoute._addFileChildren(AuthenticatedDogsRouteChildren)

interface AuthenticatedReportsMessagesTemplatesRouteChildren {
  AuthenticatedReportsMessagesTemplatesTemplateIdRoute: typeof AuthenticatedReportsMessagesTemplatesTemplateIdRoute
  AuthenticatedReportsMessagesTemplatesIndexRoute: typeof AuthenticatedReportsMessagesTemplatesIndexRoute
}

const AuthenticatedReportsMessagesTemplatesRouteChildren: AuthenticatedReportsMessagesTemplatesRouteChildren =
  {
    AuthenticatedReportsMessagesTemplatesTemplateIdRoute:
      AuthenticatedReportsMessagesTemplatesTemplateIdRoute,
    AuthenticatedReportsMessagesTemplatesIndexRoute:
      AuthenticatedReportsMessagesTemplatesIndexRoute,
  }

const AuthenticatedReportsMessagesTemplatesRouteWithChildren =
  AuthenticatedReportsMessagesTemplatesRoute._addFileChildren(
    AuthenticatedReportsMessagesTemplatesRouteChildren,
  )

interface AuthenticatedReportsMessagesRouteChildren {
  AuthenticatedReportsMessagesAssistantRoute: typeof AuthenticatedReportsMessagesAssistantRoute
  AuthenticatedReportsMessagesEquipmentChiefRoute: typeof AuthenticatedReportsMessagesEquipmentChiefRoute
  AuthenticatedReportsMessagesSecretaryRoute: typeof AuthenticatedReportsMessagesSecretaryRoute
  AuthenticatedReportsMessagesTemplatesRoute: typeof AuthenticatedReportsMessagesTemplatesRouteWithChildren
  AuthenticatedReportsMessagesVeterinaryRoute: typeof AuthenticatedReportsMessagesVeterinaryRoute
  AuthenticatedReportsMessagesIndexRoute: typeof AuthenticatedReportsMessagesIndexRoute
  AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute: typeof AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute
}

const AuthenticatedReportsMessagesRouteChildren: AuthenticatedReportsMessagesRouteChildren =
  {
    AuthenticatedReportsMessagesAssistantRoute:
      AuthenticatedReportsMessagesAssistantRoute,
    AuthenticatedReportsMessagesEquipmentChiefRoute:
      AuthenticatedReportsMessagesEquipmentChiefRoute,
    AuthenticatedReportsMessagesSecretaryRoute:
      AuthenticatedReportsMessagesSecretaryRoute,
    AuthenticatedReportsMessagesTemplatesRoute:
      AuthenticatedReportsMessagesTemplatesRouteWithChildren,
    AuthenticatedReportsMessagesVeterinaryRoute:
      AuthenticatedReportsMessagesVeterinaryRoute,
    AuthenticatedReportsMessagesIndexRoute:
      AuthenticatedReportsMessagesIndexRoute,
    AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute:
      AuthenticatedReportsMessagesRoleCategoryDocumentIdRoute,
  }

const AuthenticatedReportsMessagesRouteWithChildren =
  AuthenticatedReportsMessagesRoute._addFileChildren(
    AuthenticatedReportsMessagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckpointsRoute: typeof AuthenticatedCheckpointsRoute
  AuthenticatedDailyPlanningRoute: typeof AuthenticatedDailyPlanningRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDogsRoute: typeof AuthenticatedDogsRouteWithChildren
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedExclusionsRoute: typeof AuthenticatedExclusionsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOperationalCasesRoute: typeof AuthenticatedOperationalCasesRoute
  AuthenticatedReportsMessagesRoute: typeof AuthenticatedReportsMessagesRouteWithChildren
  AuthenticatedSectionsRoute: typeof AuthenticatedSectionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckpointsRoute: AuthenticatedCheckpointsRoute,
  AuthenticatedDailyPlanningRoute: AuthenticatedDailyPlanningRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDogsRoute: AuthenticatedDogsRouteWithChildren,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedExclusionsRoute: AuthenticatedExclusionsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOperationalCasesRoute: AuthenticatedOperationalCasesRoute,
  AuthenticatedReportsMessagesRoute:
    AuthenticatedReportsMessagesRouteWithChildren,
  AuthenticatedSectionsRoute: AuthenticatedSectionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
